./fio_nvme_single.sh nvme0 randwrite 
./fio_nvme_single.sh nvme1 randwrite
./fio_nvme_single.sh nvme2 randwrite
./fio_nvme_single.sh nvme3 randwrite
./fio_nvme_single.sh nvme4 randwrite
./fio_nvme_single.sh nvme5 randwrite
./fio_nvme_single.sh nvme6 randwrite
./fio_nvme_single.sh nvme7 randwrite
./fio_nvme_single.sh nvme8 randwrite
./fio_nvme_single.sh nvme9 randwrite
./fio_nvme_single.sh nvme10 randwrite
./fio_nvme_single.sh nvme11 randwrite
./fio_nvme_single.sh nvme13 randwrite
./fio_nvme_single.sh nvme14 randwrite
./fio_nvme_single.sh nvme15 randwrite
./fio_nvme_single.sh nvme16 randwrite
