
./fio_nvme_single.sh nvme0 read 1
./fio_nvme_single.sh nvme1 read 1
./fio_nvme_single.sh nvme2 read 1
./fio_nvme_single.sh nvme3 read 1
#./fio_nvme_single.sh nvme4 read 1
./fio_nvme_single.sh nvme5 read 1
./fio_nvme_single.sh nvme6 read 1
./fio_nvme_single.sh nvme7 read 1
./fio_nvme_single.sh nvme8 read 1
./fio_nvme_single.sh nvme9 read 1
./fio_nvme_single.sh nvme10 read 1
./fio_nvme_single.sh nvme11 read 1
./fio_nvme_single.sh nvme12 read 1
./fio_nvme_single.sh nvme13 read 1
./fio_nvme_single.sh nvme14 read 1
./fio_nvme_single.sh nvme15 read 1
./fio_nvme_single.sh nvme16 read 1
./fio_nvme_single.sh nvme17 read 1
./fio_nvme_single.sh nvme18 read 1
./fio_nvme_single.sh nvme19 read 1
#./fio_nvme_single.sh nvme21 read 1
#./fio_nvme_single.sh nvme22 read 1
./fio_nvme_single.sh nvme23 read 1
./fio_nvme_single.sh nvme24 read 1

./fio_nvme_single.sh nvme0 randread 8
./fio_nvme_single.sh nvme1 randread 8
./fio_nvme_single.sh nvme2 randread 8
./fio_nvme_single.sh nvme3 randread 8
#./fio_nvme_single.sh nvme4 randread 8
./fio_nvme_single.sh nvme5 randread 8
./fio_nvme_single.sh nvme6 randread 8
./fio_nvme_single.sh nvme7 randread 8
./fio_nvme_single.sh nvme8 randread 8
./fio_nvme_single.sh nvme9 randread 8
./fio_nvme_single.sh nvme10 randread 8
./fio_nvme_single.sh nvme11 randread 8
./fio_nvme_single.sh nvme12 randread 8
./fio_nvme_single.sh nvme13 randread 8
./fio_nvme_single.sh nvme14 randread 8
./fio_nvme_single.sh nvme15 randread 8
./fio_nvme_single.sh nvme16 randread 8
./fio_nvme_single.sh nvme17 randread 8
./fio_nvme_single.sh nvme18 randread 8
./fio_nvme_single.sh nvme19 randread 8
#./fio_nvme_single.sh nvme21 randread 8
#./fio_nvme_single.sh nvme22 randread 8
./fio_nvme_single.sh nvme23 randread 8
./fio_nvme_single.sh nvme24 randread 8
